// <auto-generated />
using System;
using Leodanny_maria_P2_AP1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leodanny_maria_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250311025257_parcial2")]
    partial class parcial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leodanny_maria_P2_AP1.Models.Ciudades", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            Monto = 1500.0,
                            NombreCiudad = "Nagua"
                        },
                        new
                        {
                            CiudadId = 2,
                            Monto = 50000.0,
                            NombreCiudad = "SFM"
                        },
                        new
                        {
                            CiudadId = 3,
                            Monto = 3.0,
                            NombreCiudad = "Villa Riva"
                        });
                });

            modelBuilder.Entity("Leodanny_maria_P2_AP1.Models.Encuestas", b =>
                {
                    b.Property<int>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncuestaId"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("EncuestaId");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("Leodanny_maria_P2_AP1.Models.EncuestasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("DetalleId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EncuestaId");

                    b.ToTable("EncuestasDetalle");
                });

            modelBuilder.Entity("Leodanny_maria_P2_AP1.Models.EncuestasDetalle", b =>
                {
                    b.HasOne("Leodanny_maria_P2_AP1.Models.Ciudades", "Ciudades")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leodanny_maria_P2_AP1.Models.Encuestas", "Encuestas")
                        .WithMany("encuestasDetalle")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudades");

                    b.Navigation("Encuestas");
                });

            modelBuilder.Entity("Leodanny_maria_P2_AP1.Models.Encuestas", b =>
                {
                    b.Navigation("encuestasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
